apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: flag-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
